# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

caltrSigmaSqC <- function(X_in, n, p) {
    .Call('hotelhd_caltrSigmaSqC', PACKAGE = 'hotelhd', X_in, n, p)
}

caltrSigma12C <- function(X1_in, X2_in, n1, n2, p) {
    .Call('hotelhd_caltrSigma12C', PACKAGE = 'hotelhd', X1_in, X2_in, n1, n2, p)
}

calcM2C <- function(Z, Omega, ndim) {
    .Call('hotelhd_calcM2C', PACKAGE = 'hotelhd', Z, Omega, ndim)
}

